{
	"version": 1744377001,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/ship-sheet0.png",
		"images/ship-sheet1.png",
		"images/shipstop-sheet0.png",
		"images/stars-sheet0.png",
		"images/bg-sheet0.png",
		"images/meteor-sheet0.png",
		"images/panel-sheet0.png",
		"images/screen-sheet0.png",
		"images/screen-sheet1.png",
		"images/screen-sheet2.png",
		"images/screen-sheet3.png",
		"images/planet-sheet0.png",
		"images/plate-sheet0.png",
		"images/plate-sheet1.png",
		"images/plate-sheet2.png",
		"images/fade-sheet0.png",
		"images/starts-sheet0.png",
		"images/planet_full-sheet0.png",
		"images/ship2-sheet0.png",
		"images/up-sheet0.png",
		"images/down-sheet0.png",
		"images/edgeup-sheet0.png",
		"images/mountain-sheet0.png",
		"images/creature-sheet0.png",
		"images/particles.png",
		"images/camerashake-sheet0.png",
		"images/sky-sheet0.png",
		"images/d-sheet0.png",
		"images/d2-sheet0.png",
		"images/shieldbar-sheet0.png",
		"images/hpbar.png",
		"images/commsmonitor-sheet0.png",
		"images/sw-sheet0.png",
		"images/sw-sheet1.png",
		"images/joystick_-sheet0.png",
		"images/joystick_-sheet1.png",
		"images/wind-sheet0.png",
		"images/up_down-sheet0.png",
		"images/particles2.png",
		"images/thrust_edge-sheet0.png",
		"images/thrust_flame-sheet0.png",
		"media/1. approaching planet’s surface. mountains ahead. gotta thread this needle real careful.m4a",
		"media/1. approaching planet’s surface. mountains ahead. gotta thread this needle real careful.ogg",
		"media/2.flying alien creatures detected… because a difficult landing wasn’t hard enough.m4a",
		"media/2.flying alien creatures detected… because a difficult landing wasn’t hard enough.ogg",
		"media/3. landing gear engaged. here goes nothing.m4a",
		"media/3. landing gear engaged. here goes nothing.ogg",
		"media/alright. one shot at this. no pressure.m4a",
		"media/alright. one shot at this. no pressure.ogg",
		"media/altitude decreasing. rocks getting bigger. life choices getting worse..m4a",
		"media/altitude decreasing. rocks getting bigger. life choices getting worse..ogg",
		"media/damn these bugs are huge.m4a",
		"media/damn these bugs are huge.ogg",
		"media/engines running hot. if i so much as think about a rough landing, this ship might explode out of spite.m4a",
		"media/engines running hot. if i so much as think about a rough landing, this ship might explode out of spite.ogg",
		"media/just me, the mountains, and an audience of hungry space-bugs.m4a",
		"media/just me, the mountains, and an audience of hungry space-bugs.ogg",
		"media/proximity alert screaming at me.m4a",
		"media/proximity alert screaming at me.ogg",
		"media/turbulence is off the charts. either this planet hates visitors or my ship hates me.m4a",
		"media/turbulence is off the charts. either this planet hates visitors or my ship hates me.ogg",
		"media/atmos.m4a",
		"media/atmos.ogg",
		"media/data sfx.m4a",
		"media/data sfx.ogg",
		"media/teleport.m4a",
		"media/teleport.ogg",
		"media/v4.m4a",
		"media/v4.ogg",
		"media/greg universe game - sfx full.m4a",
		"media/greg universe game - sfx full.ogg",
		"media/beep.m4a",
		"media/beep.ogg",
		"media/static.m4a",
		"media/static.ogg",
		"media/v1.m4a",
		"media/v1.ogg",
		"media/v3.m4a",
		"media/v3.ogg",
		"media/v2.m4a",
		"media/v2.ogg",
		"media/atmos 2.m4a",
		"media/atmos 2.ogg",
		"media/insect clash.m4a",
		"media/insect clash.ogg",
		"media/insect buzz.m4a",
		"media/insect buzz.ogg",
		"media/ship fall.m4a",
		"media/ship fall.ogg",
		"media/mountain clash.m4a",
		"media/mountain clash.ogg",
		"media/1. landing.m4a",
		"media/1. landing.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}